version: '3.8'
services:
  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PROCESSING_DB_USER=docker
      - PROCESSING_DB_PASSWORD=docker
      - PROCESSING_DB_NAME=processing
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
  app:
    build:
      context: ./processingservice
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/processing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - '8080:8080'